# Generated by Django 5.1.7 on 2025-04-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='header_image',
            field=models.ImageField(default='headers/default_header.jpg', upload_to='services/headers/'),
        ),
        migrations.AddField(
            model_name='service',
            name='strengths_image',
            field=models.ImageField(blank=True, upload_to='services/strengths/'),
        ),
    ]
