# Generated by Django 5.1.7 on 2025-04-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_header_image_service_strengths_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='strengths_text',
            field=models.TextField(blank=True, default='Notre expertise dans ce domaine inclut :\n- Solution personnalisée\n- Technologie de pointe\n- Support premium', max_length=500, verbose_name='Atouts clés'),
        ),
        migrations.AlterField(
            model_name='service',
            name='header_image',
            field=models.ImageField(default='services/headers/default_header.jpg', upload_to='services/headers/'),
        ),
    ]
