# Generated by Django 5.0.6 on 2025-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_strengths_text_alter_service_header_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (plus petit chiffre en premier)"),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Cocher pour afficher ce service en page d'accueil"),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Utilisez les classes Font Awesome. Ex: code → fa-code', max_length=50),
        ),
    ]
